version: "3.8"

services:
 # api:
  db:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5436:5432

 # consumer:

 # kafka:

 # zoo: